### PR TITLE
add app settings

### PR DESCRIPTION
**Pull request by WeeJeWel**
This PR adds the ability to add `app.json->settings` to your Homey app. These are very similar to driver settings.

### CODE REVIEW

**Comment by tjallingt** [comment]
Oh that's really nice 👍

**Review by tjallingt — APPROVED** [review]

**Review by RobinBol — APPROVED** [review]
LGTM

**Comment by RobinBol** [comment]
@WeeJeWel is this ready to be released?

**Comment by WeeJeWel** [comment]
Yes. It should not break anything because Homey does not do anything with it yet.

**Pull request merged**
