### PR TITLE
fix: throw custom capabilities with dot, increase meter_water decimals to 3 #patch

### PR DESCRIPTION
**Pull request by RobinBol**

### CODE REVIEW

**Review by WeeJeWel — APPROVED** [review]

**Comment by BOverdevest** [comment]
Wil the changes in no of digits also be updated in the documentation?
https://tools.developer.homey.app/docs/apps-reference
Or does that flow automatically?

**Comment by RobinBol** [comment]
@BOverdevest thanks, that should be updated by now!

**Comment by SiskoBen** [comment]
When will this update (changing the watermeter decimals to be 3 instead of 2) be implemented on the actual Homey devices?

**Comment by RobinBol** [comment]
> When will this update (changing the watermeter decimals to be 3 instead of 2) be implemented on the actual Homey devices?

It should be available if you are on the latest Homey firmware (7.1.0) and mobile app version (6.8.0). You _may_ need to re-pair the device, not sure about that.

**Comment by SiskoBen** [comment]
Thanks @RobinBol ,
I'll just have to wait then for my Homey to be updated to this 7.1.0 version, it is currently on v7.0.1 (it automatically updated to that 8 days ago)

**Comment by SiskoBen** [comment]
@RobinBol, 
2 days ago my Homey has updated itself to v7.1.0 and I confirmed that the Watermeter is now capable of accepting and displaying  0.001 changes of it's 'meter_water' property.

This means I can now simplify the watermeter  update flows to skip buffering watermeter pulses in a 'bucket'-variable and on every 10 pulses empty the buffer bucket (actually transfer 10 liters from it) to the watermeter 'meter_water' property. 

PS: The actual pulses come from a selfbuild sensor using an esp8266 with two inductive probes above the rotating half-moon-wheel and the Homey watermeter is an actual virtual device being updated by flows triggered from the sensor.

Thanks again.

**Comment by SiskoBen** [comment]
Now we just have to wait until the Insights page is updated as well to show the 3 digits (the graph does move according to the 3 digits but the pop-up label only shows 2 digits).
image

**Comment by WeeJeWel** [comment]
> Now we just have to wait until the Insights page is updated as well to show the 3 digits (the graph does move according to the 3 digits but the pop-up label only shows 2 digits).
> image

@jeroenwienk

**Comment by jeroenwienk** [comment]
> Now we just have to wait until the Insights page is updated as well to show the 3 digits (the graph does move according to the 3 digits but the pop-up label only shows 2 digits).
> image

This will be fixed in a future Homey release. Probably 7.1.3.

**Pull request merged**
