### PR TITLE
Turn errors into readable text

### PR DESCRIPTION
**Pull request by tjallingt**
from 

```
✖ Homey App did not validate against level `debug`:
[
    {
        "keyword": "maximum",
        "dataPath": ".sdk",
        "schemaPath": "#/properties/sdk/maximum",
        "params": {
            "comparison": "<=",
            "limit": 2,
            "exclusive": false
        },
        "message": "should be <= 2"
    }
]
Not installing, please fix the validation issues first
```

to

```
✖ Homey App did not validate against level `debug`:
manifest.sdk should be <= 2
Not installing, please fix the validation issues first
```

### CODE REVIEW

**Comment by WeeJeWel** [comment]
This should be tested thoroughly for all kinds of errors.

**Comment by WeeJeWel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WeeJeWel/node-homey-lib/pullRequest?prid=4790044&bid=15949355)

**Comment by tjallingt** [comment]
Its part of the library generating the errors, and all it is doing is joining the `error.path` and `error.message` properties of all errors returned by validate.

While it might be a little overwhelming when there are a lot of errors we might even want to enable `allErrors` (and set the `seperator` to `"\n"`) so that it collects and displays all errors at once.

```
✖ Homey App did not validate against level `debug`:
manifest should have required property 'id'
manifest should have required property 'name'
manifest should have required property 'author'
manifest should have required property 'version'
manifest should have required property 'compatibility'
manifest.drivers[0].pair[0].id should be string
manifest.drivers[0].pair[3].id should be string
Not installing, please fix the validation issues first
```

**Comment by WeeJeWel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WeeJeWel/node-homey-lib/pullRequest?prid=4790044&bid=15949355)

**Comment by tjallingt** [comment]
Latest commit gives these errors when making some subtle errors in a complicated part of the schema

```
✖ Homey App did not validate against level `debug`:
manifest.speech['en'].element['actionWords'].type should be equal to one of the allowed values ["string","regex","device","pos"]
manifest.speech should be array
manifest.speech matched no available schemas, see previous errors
Not installing, please fix the validation issues first
```

**Comment by WeeJeWel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WeeJeWel/node-homey-lib/pullRequest?prid=4790044&bid=15949355)

**Comment by tjallingt** [comment]
all possible error messages can be seen here:
https://github.com/epoberezkin/ajv/blob/12e1655bd1401e3ae5161e251ef481e4bb1ed569/lib/dot/errors.def#L93-L123

Some of these error messages do lack actionable information, see `anyOf`, `const`, `contains`, `enum`, `not` and `oneOf`. We appear to only use `oneOf` and `enum` at this moment so i added some logic to improve these error messages.

**Comment by tjallingt** [comment]
<details>
<summary>`oneOf` causes the worst types of error messages:</summary>

```
[
  {
    keyword: 'enum',
    dataPath: '.drivers[0].settings[0].type',
    schemaPath: '#/items/oneOf/0/properties/type/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  },
  {
    keyword: 'type',
    dataPath: '.drivers[0].settings[0].value',
    schemaPath: '#/items/oneOf/1/properties/value/type',
    params: { type: 'number' },
    message: 'should be number'
  },
  {
    keyword: 'enum',
    dataPath: '.drivers[0].settings[0].type',
    schemaPath: '#/items/oneOf/2/properties/type/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  },
  {
    keyword: 'required',
    dataPath: '.drivers[0].settings[0]',
    schemaPath: '#/items/oneOf/2/required',
    params: { missingProperty: 'values' },
    message: "should have required property 'values'"
  },
  {
    keyword: 'enum',
    dataPath: '.drivers[0].settings[0].type',
    schemaPath: '#/items/oneOf/3/properties/type/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  },
  {
    keyword: 'type',
    dataPath: '.drivers[0].settings[0].value',
    schemaPath: '#/items/oneOf/3/properties/value/type',
    params: { type: 'boolean' },
    message: 'should be boolean'
  },
  {
    keyword: 'enum',
    dataPath: '.drivers[0].settings[0].type',
    schemaPath: '#/items/oneOf/4/properties/type/enum',
    params: { allowedValues: [Array] },
    message: 'should be equal to one of the allowed values'
  },
  {
    keyword: 'required',
    dataPath: '.drivers[0].settings[0]',
    schemaPath: '#/items/oneOf/4/required',
    params: { missingProperty: 'children' },
    message: "should have required property 'children'"
  },
  {
    keyword: 'oneOf',
    dataPath: '.drivers[0].settings[0]',
    schemaPath: '#/items/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
```
</details>

With this PR the error looks like this:

```
✖ Homey App did not validate against level `debug`:
manifest.drivers[0].settings[0].type should be equal to one of the allowed values ["text","password","textarea","label"]
manifest.drivers[0].settings[0].value should be number
manifest.drivers[0].settings[0].type should be equal to one of the allowed values ["radio","dropdown"]
manifest.drivers[0].settings[0] should have required property 'values'
manifest.drivers[0].settings[0].type should be equal to one of the allowed values ["checkbox"]
manifest.drivers[0].settings[0].value should be boolean
manifest.drivers[0].settings[0].type should be equal to one of the allowed values ["group"]
manifest.drivers[0].settings[0] should have required property 'children'
manifest.drivers[0].settings[0] matched no available schemas, see previous errors
Not installing, please fix the validation issues first
```

For posterity's sake, an ideal error might look something like this:

``` 
✖ Homey App did not validate against level `debug`:
manifest.drivers.driver_id.settings.setting_id failed to match a schema
  option 1
    setting_id.type should be equal to one of the allowed values ["text","password","textarea","label"]

  option 2
    setting_id.value should be number

  option 3
    setting_id.type should be equal to one of the allowed values ["radio","dropdown"]
    setting_id should have required property 'values'

  option 4
    setting_id.type should be equal to one of the allowed values ["checkbox"]
    setting_id.value should be boolean

  option 5
    setting_id.type should be equal to one of the allowed values ["group"]
    setting_id should have required property 'children'
Not installing, please fix the validation issues first
```

**Pull request merged**
