### PR TITLE
added home energy monitor class

### PR DESCRIPTION
**Pull request by MatthewWaanders**
For devices that measure a home's power usage,

### CODE REVIEW

**Comment by jeroenvollenbrock** [comment]
I'd prefer to call this class `energymonitor` instead of `homeenergymonitor`, since `home` doesn't really add any meaning or value

**Comment by WeeJeWel** [comment]
Why a separate class? I think sensor does the job well. Adding a capability option that enables a zone selector for which zone this device measures the power seems like a more scalable solution to me.

**Comment by MatthewWaanders** [comment]
Fair point, that would IMO need an extension of the pair process for these device to include the selection of a zone for these capabilities. And the option to set it again afterwards might they move devices around.

**Comment by WeeJeWel** [comment]
We could do it similar to virtualClass. If we begin with defaulting to the root zone, it's easy but later on prevents a headache when we want to extend to sub-zones.

**Comment by WeeJeWel** [comment]
Please create a PR with a capability option.

**Pull request closed without merging**
